# Verify that when the package is installed on a macOS system, it eventually
# begins capturing speech events through the text-to-speech voice.
name: macOS TTS Voice Integration

on: [push, pull_request]

jobs:
  voiceover-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15, macos-26, macos-27, macos-15-intel, macos-26-intel]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup Environment
        uses: guidepup/setup-action@0.16.0

      - name: Install the package from npm
        run: npm install @bocoup/macos-at-driver-server@0.1.2

      - name: Configure the system to support the AT Driver server
        env:
          DEBUG: "*"
        working-directory: node_modules/.bin
        run: ./at-driver install --unattended

      - name: Detect voice integration
        working-directory: node_modules/.bin
        run: ../../scripts/wait-for-server.sh
